name: BadgeGuard
channels:
  - pytorch
  - nvidia         
  - conda-forge
  - defaults
dependencies:
  - python=3.11     
  - numpy
  - pillow
  - opencv          
  - pytorch
  - torchvision
  - fastapi
  - uvicorn
  - pip
  - pip:
    - ultralytics   